title: Madhavi Kapadia's Portfolio
logo: /assets/img/logo.png
description: Hi! I am a graduate student pursing her Masters in Business Analytics from the College of William and Mary and this is my portfolio. 
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
