title: Madhavi Kapadia's Portfolio
logo: false
description: Hi! I am a graduate student pursing her Masters in Business Analytics from The College of William and Mary and this is my portfolio. 
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
